"""GitHub Pull Request Atlantis-style plan diff commenter (UC504)."""
from __future__ import annotations

import logging
from typing import Any, Dict

logger = logging.getLogger(__name__)


def generate_pr_plan_comment(
    stack_name: str,
    plan_summary: Dict[str, Any],
    commit_sha: str,
) -> str:
    """Format an Atlantis-style markdown comment detailing OpenTofu execution plan changes (UC504)."""
    stk = stack_name.strip()
    short_sha = commit_sha[:7] if commit_sha else "HEAD"
    add_count = plan_summary.get("add", 0)
    change_count = plan_summary.get("change", 0)
    destroy_count = plan_summary.get("destroy", 0)
    raw_diff = plan_summary.get("raw_diff", "No changes detected.")

    lines = [
        f"#### 🚀 RADAS Plan Result for Stack: `{stk}`",
        f"*Commit: `{short_sha}`*",
        f"**Plan:** {add_count} to add, {change_count} to change, {destroy_count} to destroy.",
        "",
        "<details><summary>Show Output</summary>",
        "",
        "```diff",
        raw_diff.strip(),
        "```",
        "",
        "</details>",
        "",
        "---",
        "*Automatically generated by RADAS IaC Engine*",
    ]

    return "\n".join(lines)
