"""PR comment OpenTofu/Terraform plan differential formatter (UC368)."""
from __future__ import annotations

from typing import Any, Dict, List


def format_pr_plan_comment(plan_summary: Dict[str, Any], stack: str) -> str:
    """Format OpenTofu plan summary into a GitHub PR markdown comment (UC368)."""
    to_add = plan_summary.get("to_add", 0)
    to_change = plan_summary.get("to_change", 0)
    to_destroy = plan_summary.get("to_destroy", 0)
    resources = plan_summary.get("resources", [])

    lines = [
        f"### 🚀 RADAS Infrastructure Plan: `{stack}`",
        f"**Plan:** {to_add} to add, {to_change} to change, {to_destroy} to destroy.",
        "",
    ]

    if resources:
        lines.append("<details><summary>Show Detailed Resource Diff</summary>")
        lines.append("")
        lines.append("| Action | Resource Address |")
        lines.append("|---|---|")
        for res in resources:
            addr = res.get("address", "unknown")
            action = res.get("action", "unknown")
            lines.append(f"| `{action}` | {addr} ({action}) |")
        lines.append("")
        lines.append("</details>")

    lines.append("")
    lines.append("*(Auto-generated by RADAS GitOps Bot)*")
    return "\n".join(lines)
