name: Build and Release Radas CLI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    name: Build Radas CLI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: ['1.23']
        include:
          - os: ubuntu-latest
            binary_name: radas
            asset_name: radas-linux
          - os: macos-latest
            binary_name: radas
            asset_name: radas-macos

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'
        cache: true
        cache-dependency-path: apps/radas-cli/go.sum

    - name: Create bin directory
      run: mkdir -p bin
      working-directory: ./apps/radas-cli

    - name: Install dependencies
      run: |
        go get github.com/fatih/color
        go get github.com/spf13/cobra
        go mod tidy
        if [[ "$RUNNER_OS" == "macOS" ]]; then
          sed -i '' '/^toolchain/d' go.mod 2>/dev/null || true
        else
          sed -i '/^toolchain/d' go.mod 2>/dev/null || true
        fi
        # Download dependencies
        GOTOOLCHAIN=local go mod download
      shell: bash
      working-directory: ./apps/radas-cli

    - name: Build
      run: |
        go build -v -o bin/${{ matrix.binary_name }} -ldflags="-X 'github.com/raizora-id/radas/apps/radas-cli/cmd.Version=${{ github.ref_name }}'" .
      working-directory: ./apps/radas-cli

    - name: Set executable permissions
      if: runner.os != 'Windows'
      run: chmod +x bin/${{ matrix.binary_name }}
      working-directory: ./apps/radas-cli

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: apps/radas-cli/bin/${{ matrix.binary_name }}
        if-no-files-found: error

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: List downloaded artifacts
      run: ls -R
      
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: Radas CLI ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: |
          radas-linux/radas
          radas-macos/radas